name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build_and_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust 1.90.0
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.90.0

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Run Tests
        run: cargo test --verbose

  lint_and_shear:
    name: Lint and Dependency Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Stable Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Rust Cache
        uses: Swatinem/rust-cache@v2

      - name: Format Check
        run: cargo fmt --all -- --check

      - name: Clippy Lint
        run: cargo clippy -- -D warnings

      - name: Install & Run cargo-shear

        run: |
          cargo install cargo-shear@1.7.0
          cargo shear
